packages:
  - packages/*
  - libs/*
  - apps/*

patchedDependencies:
  electron-vite: patches/electron-vite.patch

catalog:
  '@unbird/eslint-config': ^1.0.2
  '@unbird/logg': ^1.1.3
  '@unbird/result': ^1.1.1
  '@xsai-ext/providers-cloud': ^0.4.0-beta.1
  '@xsai-ext/providers-local': ^0.4.0-beta.1
  '@xsai/embed': ^0.4.0-beta.1

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - bufferutil
  - electron
  - electron-winstaller
  - es5-ext
  - esbuild
  - sharp
  - unrs-resolver
  - utf-8-validate
  - vue-demi
  - websocket
