# Database settings
database:
  # Database type: postgres, pglite
  type: postgres

  # PostgreSQL configuration (used when type: postgres)
  host: localhost
  port: 5433
  user: postgres
  password: '123456'
  database: postgres

# API settings
api:
  # Telegram API settings
  telegram:
    # Get these values from https://my.telegram.org/apps
    apiId: '611335'
    apiHash: d524b414d21f4d37f08684c1df41ac9c
    receiveMessage: false
    # Optional proxy settings
    # proxy:
    #   ip: ''            # Proxy host (IP or hostname)
    #   port: 0          # Proxy port
    #   MTProxy: false   # Whether it's an MTProxy or a normal Socks proxy
    #   secret: ''       # If using MTProxy, provide a secret
    #   socksType: 5     # If using Socks, choose 4 or 5
    #   timeout: 2       # Timeout (in seconds) for connection
    #   username: ''     # Optional username for proxy auth
    #   password: ''     # Optional password for proxy auth
  # Embedding settings
  embedding:
    # Embedding provider (openai or ollama)
    provider: openai
    # Embedding model
    model: text-embedding-3-small
    # API key for provider
    apiKey: your_openai_api_key
    # Optional, available dimensions: 1536, 1024, 768. Default dimension is 1536. #If using gemini-embedding-exp-03-07, choose 768
    dimension: 1536
    # Optional, for custom API providers
    apiBase: 'https://api.openai.com/v1'
