name: autofix.ci

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: pnpm/action-setup@v3
      - uses: actions/setup-node@v5
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install
      - run: pnpm prune && pnpm dedupe
      - run: pnpm run lint:fix

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
